fullscreen=yes
profile=gpu

scale=spline36
cscale=spline36
dscale=mitchell

# Mantener el debanding activo (evita degradados pixelados)
deband=yes
deband-iterations=1
deband-threshold=48
deband-range=16

video-sync=display-resample
#interpolation
#tscale=mitchell

hwdec=vaapi

screenshot-format=png
screenshot-png-compression=8
screenshot-template='~/%F (%P) %n'

volume-max=600
af=scaletempo2

ytdl-format=bestvideo[height<=?1080][fps<=?60][vcodec!=?vp9][protocol!=http_dash_segments]+bestaudio/best
